# Generated by Django 4.2.7 on 2024-05-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("realowner", "0002_userprofile_transferred_items_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_user",
                to="realowner.userprofile",
            ),
        ),
    ]
