# Generated by Django 4.2.7 on 2024-05-29 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realowner", "0003_alter_item_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
